### ISSUE TITLE
Goslin compilation installation on Windows

### ISSUE THREAD

**Issue by rbarreror** [lifs-tools/cppgoslin#1]
I am developing a metabolomic bioinformatic tool for the processing of the name of different types of metabolites, and I would like to implement Goslin (C++ version) to it. I have seen that goslin has a makefile that allows an easy compilation and installation of the library on Unix, but I would like to implement it on Windows. Is there a way to install and compile this library on Windows? One option is to compile and install it manually following makefile instructions but it may be slow and unstable. What do you recommed me?

Thanks and congratulations!

**Comment by dominik-kopczynski** [comment]
Hi Rafael, Thank you for the question. There are several ways to compile the library on Windows. What IDE are you using? Would it be helpful for you, if we would provide a project file in Visual Studio? A workaround would also be to install g++ and make for Windows. In future, we will provide precompiled libraries for download.
Cheers, Dominik

**Comment by rbarreror** [comment]
Hi Dominik! Thank you very much for your reply. I am using Build tools for Visual Studio along with Visual Studio Code. Hence, if you provide a project file in Visual Studio I could try. In any case, using g++ and make for Windows could be a good option, so I will try it too.
Again thank you very much.
Rafael
